FROM openliberty/open-liberty:21.0.0.3-full-java15-openj9-ubi

# Add config
COPY --chown=1001:0  build/wlp/usr/servers/defaultServer/server.xml /config/

# COPY --chown=1001:0  build/wlp/usr/servers/defaultServer/bootstrap.properties /config/

#Add App
COPY --chown=1001:0  build/wlp/usr/servers/defaultServer/configDropins/overrides/liberty-plugin-variable-config.xml /config/configDropins/overrides/

COPY --chown=1001:0 build/libs/BasicV3.war /config/apps/

RUN configure.sh